name: Update Submodules

on:
  # Runs once a month or on push
  schedule:
    - cron: '0 0 1 * *'   
  push:
    branches:
      - 'main'
jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'  # Ensure submodules are checked out as well

      - name: Reset submodules to the latest commit (hard reset)
        run: |
          # Update submodules to the latest commit from their repositories
          git submodule update --remote --recursive
          
          # Reset each submodule to its latest commit (to fix unrelated histories)
          git submodule foreach 'git reset --hard HEAD'  # Hard reset for each submodule

      - name: Update submodules to latest commit
        run: |
          git submodule update --remote --merge  # Update to the latest commit of each submodule
          git add .  # Stage the updated submodule references
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"  # Commit the updates if there are any
          git push  # Push the changes to the repository
